/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.oo00spy00oo.grpc.error;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
